### ISSUE TITLE
Prepare list of models/approaches to use for ensemble model

### ISSUE THREAD

**Issue by dchaplinsky** [lang-uk/ner-uk#11]
My preliminary research yielded following models that was successfully trained using our data:

- MITIE, our baseline
- Heuristic based + MITIE approach from @Amice13, who used heuristics to find entities and MITIE to classify them
- Polyglot, trained on wikipedia data
- Stanza, trained by @gawy on lang-uk data
- [BERT based model by @nazarii-piontko](https://github.com/nazarii-piontko/ner-ua)

[There is also prototype of NER, made by Konstantyn Kuznetsov](http://pullenti.ru) which is heuristic based and has wide number of entity classes.

Please evaluate available models and their tagset to finalize the list of models for our ensemble model. Any other ideas on the models I'm missing are very welcome

**Comment by dchaplinsky** [comment]
@Amice13 please let me know if it's possible/feasibly to wrap your homebrew mixed model and add it to the mix

**Comment by gawy** [comment]
The decision is to start with 3 models for this iteration and after get to some ensemble that is acceptable we'll look into adding more models.

The three to go now are:
- MITIE - as we already have it in the pool and it would probably be relatively easy to retrain on a new data set
- Stanza - larger model with better performance but we also have a good foundation to update it
- Something from transformers - these larger and more advanced models have high potential to have the best performance if our data set is large enough.

The plan is also to use existing Polyglot models to compare with or as part of the ensemble.
The next candidate is Spacy.
