### ISSUE TITLE
Топоніми

### ISSUE THREAD

**Issue by velmyshanovnyi** [lang-uk/ner-uk#5]
маю структуровану і вичишену базу КОАТУУ, можу злити як NER контент...
(Класифікатор об'єктів адміністративно-територіального устрою України)

....якщо ще не юзаєте...

**Comment by velmyshanovnyi** [comment]
ага, ще згадав, є прелік ВУЛИЦЬ... (власна назва, чи як?)
для усіх міст чи то 3 чи то 8 якихось областей....

**Comment by vseloved** [comment]
Чудово!
Міг би це додати у проект https://github.com/lang-uk/ua-gazetteers ?

**Comment by velmyshanovnyi** [comment]
https://github.com/lang-uk/ua-gazetteers/upload/master

Uploads are disabled.
File uploads require push access to this repository.

**Comment by vseloved** [comment]
Треба зробити fork, додати файли, потім pull-reuqest. Це ж стандартний метод гітхабу.

**Comment by velmyshanovnyi** [comment]
люблю через веб інтерфейс лити :)

П.С.
прийми мій інвайт в хенгауті

**Comment by velmyshanovnyi** [comment]
або додай мене в мембери lang-uk

**Comment by vseloved** [comment]
а що за хенгаут? гугл

**Comment by velmyshanovnyi** [comment]
так, гул чат, в пошті є - чи окремим додатком в браузер,
чи скайп "velmyshanovnyi"

**Comment by vseloved** [comment]
вислав запрошення у наш слек-чат

**Comment by dchaplinsky** [comment]
В мене був перелік вулиць по всій Україні, але він трохи застарілий, немає свіжоперейменованих.

**Comment by velmyshanovnyi** [comment]
суть в тому що старі назви теж треба зберігати,
нові можу дістати якщо треба
