### ISSUE TITLE
Додати датасет

### ISSUE THREAD

**Issue by Pryanic** [lang-uk/ner-uk#9]
Привіт я в рамках своєї роботи перевів розмічений датасет imdb на українську мову. Тепер шукаю місце де покласти цей датасет. Мені здається, що ваш проект це гарне місце. 
Опис датасету
28 000 файлів кожне до 1000 символів 
14 000 позитивних текстів і 14 000 негативніх
Файли були отримані шляхом машинного перекладання текстів з англійської. Тексти перекладені частково через брак грошей але цього датасету достатьно для перевірки деяких моделей і це краще ніж нічого. Якщо вам цікаво то напишіть

**Comment by velmyshanovnyi** [comment]
а можна невеликий семпл?

**Comment by Pryanic** [comment]
Так звичайно, зараз наведу кілька перших речень з декількох файлів. Ще раз наголошую це машинний переклад на українську мову
Позитивні
'Секс, наркотики, расизм і, звичайно, ви ABC. Що ще можна захотіти в дитячому шоу'

> Режисер любить актрису і це показує. Актриса населяє персонажа, якого ми любимо з першого погляду та звучання.

> Дивовижно кумедна, вражаюча особливість піонерів туртаблізму. DJ Shadow та Q-Bert вражають цим надзвичайним документальним фільмом. Перегляньте майже кожного головного ді-джея, який зараховує їх на подряпину завдяки класиці Herbie Hancoc

> Я просто хотів би сказати, що The Cure був чудовим фільмом, який допомагає інформувати про те, як люди, які мають ВІЛ-позитивних людей, повинні функціонувати в житті.

> Надзвичайно чарівна Сюзі Делер грає артиста статуї, одержимого успіхом у театрі. Її чоловік і акомпаніатор, якого грає Бернард Блієр, - складна, але ревна людина

Тепер  негативні

> Первинний сюжет! Первинний напрямок! Погане тлумачення

> Десять хвилин людей, що лунають галонами рожевої блювоти. Повторювані сцени величезної купи собачих екскрементів - потрібно сказати більше ??

> Zipperface - це такий досвід, якого потрібно чекати протягом усього життя! Мансур Порманд - один з найгірших режисерів усіх часів! Якщо ви любите погані фільми, дивіться це за будь-яку ціну

> УГГ! ... це найгірша боротьба з рестлеманією .... немає хороших матчів ..... Халк Хоган знову в головному заході отримує над засмаглою лисиною голову! Одне зауваження, гідне на цій стрічці. 1 з 10 зірок WOOF !!

> Мушу визнати, що це один з найгірших фільмів, який я бачив. Я думав, що у Деніса Хоппера трохи більше смаку, ніж з&#39;являтися в такому роді yeeeecchh. Якщо це повинно бути смішним, то я повинен оглянути нове почуття гумору. Якщо ви думаєте придбати цей фільм, краще подумайте ще раз

**Comment by Pryanic** [comment]
@velmyshanovnyi

**Comment by dchaplinsky** [comment]
Hello @Pryanic.

Sorry for the late reply, for some reason I wasn't subscribed to issues in this repo.

I think that this might be a separate dataset (not connected to NER-UK).
Could you please provide methodology (which translator, etc) and wider sample (like 10 texts of each category).

We'll discuss that on our next meeting of lang-uk initiative
